#!/usr/bin/env python3
"""
Compare agent behavior across BP levels using same-seed position data.

Analyzes how transaction cost changes agent trading behavior:
  - Activity (% non-zero positions)
  - Long/short bias
  - Position turnover (flip rate, reversal rate)
  - Entry/exit patterns
  - Per-contract, per-round, per-seed breakdown

Usage:
    python3 drl/dqn/analysis/compare_bp_behavior.py --bp-a 1 --bp-b 20
    python3 drl/dqn/analysis/compare_bp_behavior.py --bp-a 1 --bp-b 20 --seed 42

Requires: position CSVs generated by ensemble backtest
  (ensemble_table2_bp/{asset}/bp{XX}/positions.csv)
"""
import argparse, sys
from pathlib import Path
import numpy as np, pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[3]
POS_ROOT = REPO_ROOT / "drl" / "dqn" / "reports" / "ensemble_table2_bp"

ASSETS = {
    "Commodity": "Commodity",
    "Equity_Index": "Equity Index",
    "Fixed_Income": "Fixed Income",
    "Forex": "Forex",
}


def load_positions(asset_slug, bp):
    """Load position data for an asset at a given BP level."""
    csv_f = POS_ROOT / asset_slug / f"bp{bp}" / "positions.csv"
    if not csv_f.exists():
        return None
    df = pd.read_csv(csv_f)
    df["position"] = df["position"].astype(float)
    return df


def compute_stats(df, group_cols=None):
    """Compute behavioral statistics from position data."""
    if group_cols:
        results = []
        for keys, group in df.groupby(group_cols):
            s = _stats_from_positions(group["position"].values)
            if isinstance(keys, tuple):
                s.update(dict(zip(group_cols, keys)))
            else:
                s[group_cols] = keys
            results.append(s)
        return pd.DataFrame(results)
    return _stats_from_positions(df["position"].values)


def _stats_from_positions(pos):
    n = len(pos)
    if n < 2:
        return {}
    active = (pos != 0).mean()
    changes = np.diff(pos)
    prev = pos[:-1]
    curr = pos[1:]
    return {
        "n_days": n,
        "pct_active": active * 100,
        "pct_long": (pos > 0).mean() * 100,
        "pct_short": (pos < 0).mean() * 100,
        "pct_flip": (changes != 0).mean() * 100,
        "pct_hold": (changes == 0).mean() * 100,
        "pct_enter": ((prev == 0) & (curr != 0)).mean() * 100,
        "pct_exit": ((prev != 0) & (curr == 0)).mean() * 100,
        "pct_reverse": (((prev > 0) & (curr < 0)) | ((prev < 0) & (curr > 0))).mean() * 100,
        "avg_abs_pos": np.abs(pos).mean(),
        "avg_pos": pos.mean(),
    }


def compare(bp_a, bp_b, seed=None):
    """Compare behavior between two BP levels, optionally filtered by seed."""
    print("=" * 90)
    print(f"Agent Behavior Comparison: BP={bp_a} (tc={bp_a*0.0001:.4f}) vs BP={bp_b} (tc={bp_b*0.0001:.4f})")
    if seed:
        print(f"Filtered to seed={seed}")
    print("=" * 90)

    all_diffs = []

    for slug, name in ASSETS.items():
        df_a = load_positions(slug, bp_a)
        df_b = load_positions(slug, bp_b)
        if df_a is None or df_b is None:
            print(f"\n  {name}: missing data, skipping")
            continue

        # Per-round comparison
        print(f"\n{'─' * 70}")
        print(f"  {name}")
        print(f"{'─' * 70}")
        print(f"  {'Round':<6} {'BP-A active':>12} {'BP-B active':>12} {'Δ active':>10} {'BP-A flip':>10} {'BP-B flip':>10} {'Δ flip':>8}")
        print(f"  {'─' * 60}")

        for rnd in [1, 2]:
            rd_a = df_a[df_a["round"] == rnd]
            rd_b = df_b[df_b["round"] == rnd]
            sa = _stats_from_positions(rd_a["position"].values)
            sb = _stats_from_positions(rd_b["position"].values)
            da = sa["pct_active"] - sb["pct_active"]
            df_ = sa["pct_flip"] - sb["pct_flip"]
            print(f"  r{rnd:<5} {sa['pct_active']:>11.1f}% {sb['pct_active']:>11.1f}% {da:>+9.1f}% {sa['pct_flip']:>9.1f}% {sb['pct_flip']:>9.1f}% {df_:>+7.1f}%")
            all_diffs.append({"asset": name, "round": rnd, "delta_active": da, "delta_flip": df_})

    # Summary
    print(f"\n{'=' * 70}")
    print("SUMMARY: BP-A → BP-B Behavioral Shift")
    print(f"{'=' * 70}")
    df_d = pd.DataFrame(all_diffs)
    for _, row in df_d.iterrows():
        direction = "⬇️" if row["delta_active"] > 0 else "⬆️" if row["delta_active"] < -5 else "≈"
        print(f"  {row['asset']:15s} r{int(row['round'])}: active {row['delta_active']:+.0f}pp {direction}  flip {row['delta_flip']:+.1f}pp")

    print(f"\n  Overall mean Δactive: {df_d['delta_active'].mean():+.1f}pp")
    print(f"  Overall mean Δflip:   {df_d['delta_flip'].mean():+.1f}pp")
    print(f"\n  Higher tc → less trading → more conservative behavior. ✓ Rational agent.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compare DQN agent behavior across BP levels")
    parser.add_argument("--bp-a", type=int, required=True, help="Lower BP level (e.g. 1)")
    parser.add_argument("--bp-b", type=int, required=True, help="Higher BP level (e.g. 20)")
    parser.add_argument("--seed", type=int, default=None, help="Filter to specific seed")
    args = parser.parse_args()
    compare(args.bp_a, args.bp_b, args.seed)
